### ISSUE TITLE
Add .travis.yml to make sure table of contents is up to date

### ISSUE THREAD

**Issue by ahmetb** [ahmetb/cloud-run-faq#1]
Something along the lines of

```yaml
language: node
install:
- npm install -g markdown-cli
script:
- markdown-toc -i README.md
- test -z "$(git diff | tee /dev/stderr)"
```
