### ISSUE TITLE
Add info about support of Cloud SQL and Memorystore

### ISSUE THREAD

**Issue by ibrunotome** [ahmetb/cloud-run-faq#8]
https://twitter.com/ibrunotome/status/1117204999581388802

**Comment by steren** [comment]
Cloud SQL support is now here, see alpha docs at: https://stackoverflow.com/questions/55693241/how-to-securely-connect-to-cloud-sql-from-cloud-run/55892255#55892255

**Comment by topiaruss** [comment]
> Cloud SQL support is now here, see alpha docs at: https://stackoverflow.com/questions/55693241/how-to-securely-connect-to-cloud-sql-from-cloud-run/55892255#55892255

Thanks, Steren.

I confirm the observation of Leonid Makarov on your linked question. 
I followed the official docs to annotate a CloudSQL in another region. The correct annotation is added to YAML, the image is started, but the /cloudsql mount directory is empty.

```
  annotations:
    serving.knative.dev/creator: someone@gmail.com
    serving.knative.dev/lastModifier: someone@gmail.com
    run.googleapis.com/cloudsql-instances: ursularity-222313:europe-west2:ursularity-2
```
